version: '3.2'
services:
  keeweb:
    image: jnvinet/keeweb
    container_name: 'keeweb'
    labels:
      - "traefik.tcp.routers.keeweb.rule=HostSNI(`${KEEWEB_ENDPOINT}`)"
      - "traefik.tcp.routers.keeweb.tls.passthrough=true"
    environment:
      - "DH_SIZE=1024"
      - "CN=${KEEWEB_ENDPOINT}"
    volumes:
      - "${EXT_DIR}:/etc/nginx/external/"
      - "${EXT_ARC}:${CON_ARC}"
    networks:
      - web

networks:
  web:
    external: true