version: '3.2'
services:
  keeweb:
    image: jnvinet/keeweb
    container_name: 'keeweb'
    labels:
      - "traefik.http.routers.keeweb.rule=Host(`${KEEWEB_ENDPOINT}`)"
      - "traefik.http.routers.keeweb.tls=true"
      - "traefik.http.services.keeweb.loadbalancer.server.port=443"
      - "traefik.http.services.keeweb.loadbalancer.server.scheme=https"
    environment:
      - "DH_SIZE=512"
      - "CN=${KEEWEB_ENDPOINT}"
#    volumes:
#      - "${EXT_DIR}:/etc/nginx/external/"
    networks:
      - web

networks:
  web:
    external: true