version: '3.2'
services:
  keeweb:
    image: jvinet/keeweb:compose
    build:
      context: .
      dockerfile: dockerfile
      args: 
        - SERVERNAME=${KEEWEB_ENDPOINT}
    container_name: 'keeweb'
    labels:
      - "traefik.http.routers.keeweb.rule=Host(`${KEEWEB_ENDPOINT}`)"
      - "traefik.http.routers.keeweb.tls=true"
      - "traefik.http.routers.keeweb.tls.certResolver=le"
      - "traefik.http.routers.keeweb.tls.domains[0].main=${DOMAIN}"
      - "traefik.http.routers.keeweb.tls.domains[0].sans[0]=*.${DOMAIN}"
      - "traefik.http.services.service01.loadbalancer.server.port=443"
      - "traefik.http.services.service01.loadbalancer.server.scheme=https"
    networks:
      - web

networks:
  web:
    external: true