version: '3.2'
services:
  keeweb:
    image: jnvinet/keeweb:latest
    container_name: 'keeweb'
    labels:
      - "traefik.http.routers.keeweb.rule=Host(`${KEEWEB_ENDPOINT}`)"
      - "traefik.http.routers.keeweb.tls=true"
      - "traefik.http.routers.keeweb.tls.certResolver=le"
      - "traefik.http.routers.keeweb.tls.domains[0].main=${DOMAIN}"
      - "traefik.http.routers.keeweb.tls.domains[0].sans[0]=*.${DOMAIN}"
    networks:
      - web
networks:
  web:
    external: true